name    'ptomulik-oval'
version '0.0.3'
source 'git://github.com/ptomulik/rubygems-oval.git'
author 'ptomulik'
license 'Apache License, Version 2.0'
summary 'Simple utility to validate Hashes of options.'
description 'Simple utility to validate Hashes of options.'
project_page 'https://gitbub.com/ptomulik/rubygems-oval'
